#!/usr/bin/env bash
# changes home ip for facebook

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
#sed -i 's/127.0.0.1/127.0.0.2/' ~/host.new
#sed -i 's/157.240.11.35/8.8.8.8/' ~/host.new
cp -f ~/hosts.new /etc/hosts
